"""Constants for the Senec integration."""
from collections import namedtuple
from datetime import timedelta
from typing import Final

from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorEntityDescription,
    SensorStateClass,
)
from homeassistant.const import (
    ELECTRIC_CURRENT_AMPERE,
    ELECTRIC_POTENTIAL_MILLIVOLT,
    ELECTRIC_POTENTIAL_VOLT,
    ENERGY_KILO_WATT_HOUR,
    PERCENTAGE,
    POWER_WATT,
    TEMP_CELSIUS,
)

DOMAIN = "senec"


"""Default config for Senec."""
DEFAULT_HOST = "Senec"
DEFAULT_NAME = "senec"

"""Fixed constants."""
SCAN_INTERVAL = timedelta(seconds=60)

"""Supported sensor types."""

SENSOR_TYPES = [
    SensorEntityDescription(
        key="system_state",
        name="System State",
        icon="mdi:solar-power",
    ),
    SensorEntityDescription(
        key="solar_generated_power",
        name="Solar Generated Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:solar-power",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="house_power",
        name="House Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:home-import-outline",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="battery_state_power",
        name="Battery State Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:home-battery",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="battery_charge_power",
        name="Battery Charge Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:home-battery",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="battery_discharge_power",
        name="Battery Discharge Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:home-battery-outline",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="battery_charge_percent",
        name="Battery Charge Percent",
        native_unit_of_measurement=PERCENTAGE,
        icon="mdi:home-battery",
        # device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="grid_state_power",
        name="Grid State Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:transmission-tower",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="grid_imported_power",
        name="Grid Imported Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:transmission-tower-import",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="grid_exported_power",
        name="Grid Exported Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:transmission-tower-export",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="wallbox_power",
        name="Wallbox Power",
        native_unit_of_measurement=POWER_WATT,
        icon="mdi:car-arrow-left",
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="wallbox_ev_connected",
        name="Wallbox EV Connected",
        icon="mdi:car-electric",
    ),
    SensorEntityDescription(
        key="house_total_consumption",
        name="House consumed",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:home-import-outline",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    SensorEntityDescription(
        key="solar_total_generated",
        name="Solar generated",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:solar-power",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    SensorEntityDescription(
        key="battery_total_charged",
        name="Battery charged",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:home-battery",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    SensorEntityDescription(
        key="battery_total_discharged",
        name="Battery discharged",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:home-battery-outline",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    SensorEntityDescription(
        key="grid_total_import",
        name="Grid Imported",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:transmission-tower-import",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    SensorEntityDescription(
        key="grid_total_export",
        name="Grid Exported",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:transmission-tower-export",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    SensorEntityDescription(
        key="wallbox_energy",
        name="Wallbox charged",
        native_unit_of_measurement=ENERGY_KILO_WATT_HOUR,
        icon="mdi:ev-station",
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    SensorEntityDescription(
        key="bms_cell_temp_A1",
        name="Cell Temperature Module A1",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_temp_A2",
        name="Cell Temperature Module A2",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_temp_A3",
        name="Cell Temperature Module A3",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_temp_A4",
        name="Cell Temperature Module A4",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_temp_A5",
        name="Cell Temperature Module A5",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_temp_A6",
        name="Cell Temperature Module A6",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_temp_B1",
        name="Cell Temperature Module B1",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_temp_B2",
        name="Cell Temperature Module B2",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_temp_B3",
        name="Cell Temperature Module B3",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_temp_B4",
        name="Cell Temperature Module B4",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_temp_B5",
        name="Cell Temperature Module B5",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_temp_B6",
        name="Cell Temperature Module B6",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_temp_C1",
        name="Cell Temperature Module C1",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_temp_C2",
        name="Cell Temperature Module C2",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_temp_C3",
        name="Cell Temperature Module C3",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_temp_C4",
        name="Cell Temperature Module C4",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_temp_C5",
        name="Cell Temperature Module C5",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_temp_C6",
        name="Cell Temperature Module C6",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_temp_D1",
        name="Cell Temperature Module D1",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_temp_D2",
        name="Cell Temperature Module D2",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_temp_D3",
        name="Cell Temperature Module D3",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_temp_D4",
        name="Cell Temperature Module D4",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_temp_D5",
        name="Cell Temperature Module D5",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_temp_D6",
        name="Cell Temperature Module D6",
        native_unit_of_measurement=TEMP_CELSIUS,
        device_class=SensorDeviceClass.TEMPERATURE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_A1",
        name="Cell Voltage Module A1",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_A2",
        name="Cell Voltage Module A2",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_A3",
        name="Cell Voltage Module A3",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_A4",
        name="Cell Voltage Module A4",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_A5",
        name="Cell Voltage Module A5",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_A6",
        name="Cell Voltage Module A6",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_A7",
        name="Cell Voltage Module A7",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_A8",
        name="Cell Voltage Module A8",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_A9",
        name="Cell Voltage Module A9",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_A10",
        name="Cell Voltage Module A10",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_A11",
        name="Cell Voltage Module A11",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_A12",
        name="Cell Voltage Module A12",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_A13",
        name="Cell Voltage Module A13",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_A14",
        name="Cell Voltage Module A14",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_B1",
        name="Cell Voltage Module B1",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_B2",
        name="Cell Voltage Module B2",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_B3",
        name="Cell Voltage Module B3",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_B4",
        name="Cell Voltage Module B4",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_B5",
        name="Cell Voltage Module B5",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_B6",
        name="Cell Voltage Module B6",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_B7",
        name="Cell Voltage Module B7",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_B8",
        name="Cell Voltage Module B8",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_B9",
        name="Cell Voltage Module B9",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_B10",
        name="Cell Voltage Module B10",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_B11",
        name="Cell Voltage Module B11",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_B12",
        name="Cell Voltage Module B12",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_B13",
        name="Cell Voltage Module B13",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_B14",
        name="Cell Voltage Module B14",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_C1",
        name="Cell Voltage Module C1",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_C2",
        name="Cell Voltage Module C2",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_C3",
        name="Cell Voltage Module C3",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_C4",
        name="Cell Voltage Module C4",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_C5",
        name="Cell Voltage Module C5",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_C6",
        name="Cell Voltage Module C6",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_C7",
        name="Cell Voltage Module C7",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_C8",
        name="Cell Voltage Module C8",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_C9",
        name="Cell Voltage Module C9",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_C10",
        name="Cell Voltage Module C10",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_C11",
        name="Cell Voltage Module C11",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_C12",
        name="Cell Voltage Module C12",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_C13",
        name="Cell Voltage Module C13",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_C14",
        name="Cell Voltage Module C14",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_D1",
        name="Cell Voltage Module D1",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_D2",
        name="Cell Voltage Module D2",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_D3",
        name="Cell Voltage Module D3",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_D4",
        name="Cell Voltage Module D4",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_D5",
        name="Cell Voltage Module D5",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_D6",
        name="Cell Voltage Module D6",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_D7",
        name="Cell Voltage Module D7",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_D8",
        name="Cell Voltage Module D8",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_D9",
        name="Cell Voltage Module D9",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_D10",
        name="Cell Voltage Module D10",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_D11",
        name="Cell Voltage Module D11",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_D12",
        name="Cell Voltage Module D12",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_D13",
        name="Cell Voltage Module D13",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_cell_volt_D14",
        name="Cell Voltage Module D14",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_MILLIVOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_voltage_A",
        name="Voltage Module A",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_voltage_B",
        name="Voltage Module B",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_voltage_C",
        name="Voltage Module C",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_voltage_D",
        name="Voltage Module D",
        native_unit_of_measurement=ELECTRIC_POTENTIAL_VOLT,
        device_class=SensorDeviceClass.VOLTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_current_A",
        name="Current Module A",
        native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_current_B",
        name="Current Module B",
        native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_current_C",
        name="Current Module C",
        native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_current_D",
        name="Current Module D",
        native_unit_of_measurement=ELECTRIC_CURRENT_AMPERE,
        device_class=SensorDeviceClass.CURRENT,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_soc_A",
        name="SOC Module A",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_soc_B",
        name="SOC Module B",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_soc_C",
        name="SOC Module C",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    SensorEntityDescription(
        key="bms_soc_D",
        name="SOC Module D",
        native_unit_of_measurement=PERCENTAGE,
        state_class=SensorStateClass.MEASUREMENT,
    ),
]
